### ISSUE TITLE
what happened to vim-sequence?

### ISSUE THREAD

**Issue by sunaku** [kurkale6ka/vim#5]
Hello,

I'm a long time user of your **vim-sequence** plugin, which suddenly ceased to exist :scream: today:

> https://github.com/kurkale6ka/vim-sequence

Was it removed intentionally?  Has it moved to a new location?  Where should I install it from?

Thanks for your consideration.

**Comment by kurkale6ka** [comment]
Hi,

I removed the repository because all the functionality it provided is builtin into recent Vim versions

Regards

**Comment by sunaku** [comment]
That's awesome! :joy_cat: I'm glad your plugin idea was Vim worthy! :trophy:  It was certainly a life changer for me. :bowing_man:
